---
- hosts: build_host
  become: true
  vars:
    build_dir: /opt/build
    puppetlabs_build_dir: /opt/pl-build-tools
    cmake_version: 3.2.3
    boost_version: 1.58.0
    gcc_version: 4.8.5
    yaml_cpp_version: 0.5.3
    swig_version: 3.0.10
    puppet_agent_version: 1.8.2
    puppet_agent_build_timestamp: "{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}:{{ ansible_date_time.second }}"
  tasks:
    - include: subplays/prep_box.yaml

- hosts: localhost
  vars:
    puppet_agent_version: 1.8.2
    puppet_agent_build_timestamp: "{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}:{{ ansible_date_time.second }}"
  tasks:
    - name: clone puppet-agent
      git:
        repo: https://github.com/puppetlabs/puppet-agent.git
        dest: "{{ playbook_dir }}/puppet-agent"
        update: false
        version: "{{ puppet_agent_version }}"

    - name: clone vanagon
      git:
        repo: https://github.com/puppetlabs/vanagon.git
        dest: "{{ playbook_dir }}/puppet-agent/vanagon"
        update: false
        version: 0.8.2

    - name: patch vanagon rpm type
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/vanagon/lib/vanagon/platform/rpm.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/vanagon/lib/vanagon/platform/rpm.rb"

    - name: patch puppet-agent project
      patch:
        src: "patches/{{ puppet_agent_version }}/puppet-agent/configs/projects/puppet-agent.rb.patch"
        dest: "{{ playbook_dir }}/puppet-agent/configs/projects/puppet-agent.rb"

    - include: subplays/puppet_agent_config_platforms.yaml
    - include: subplays/puppet_agent_config_components.yaml
    - include: subplays/puppet_agent_bundle_updates.yaml

    - name: build puppet-agent
      shell: "/bin/bash --login -c 'source ~/.rvm/scripts/rvm && rvm_is_not_a_function=0 rvm use 2.2.1@puppet-agent-build && VANAGON_SSH_KEY=~/.ssh/id_rsa VANAGON_RETRY_COUNT=3 VANAGON_LOCATION=file://{{ playbook_dir }}/puppet-agent/vanagon bundle exec build puppet-agent el-{{ hostvars[item]['el_version'] }}-{{ hostvars[item]['el_arch'] }} {{ item }}'"
      args:
        chdir: "{{ playbook_dir }}/puppet-agent"
      with_items: "{{ groups['build_host'] }}"

- hosts: build_host
  vars:
    puppet_agent_build_timestamp: "{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}:{{ ansible_date_time.second }}"
  become: true
  tasks:
    - name: find srpm
      shell: "find /var/tmp/tmp.* -name *src.rpm"
      register: srpm_path

    - name: create arch destination directory
      file:
        dest: "{{ playbook_dir }}/SRPMs/{{ puppet_agent_build_timestamp }}/{{ el_arch }}"
        state: directory
        recurse: true

    - name: get srpm from host
      fetch:
        src: "{{ item }}"
        dest: "{{ playbook_dir }}/SRPMs/{{ puppet_agent_build_timestamp }}/{{ el_arch }}/"
        flat: true
      with_items: "{{ srpm_path.stdout.split('\n') }}"
