---
- hosts: build_host
  become: true
  vars:
    build_dir: /opt/build
    puppetlabs_build_dir: /opt/pl-build-tools
    cmake_version: 3.2.3
    boost_version: 1.58.0
    gcc_version: 4.8.5
    yaml_cpp_version: 0.5.3
    swig_version: 3.0.10
    puppet_agent_version: 1.8.2
  tasks:
    - name: disable selinux
      command: setenforce 0

    - name: install packages
      yum:
        name: "{{ item }}"
      with_items:
        - make
        - imake
        - gcc
        - gcc-c++
        - python-devel
        - bzip2-devel
        - libselinux-python
        - wget
        - bzip2
        - zip
        - pcre-devel
        - vim # for if/when ssh'ing in
      register: install_pkgs_result
      until: install_pkgs_result | succeeded
      retries: 5

    - include: subplays/gcc.yaml
    - include: subplays/cmake.yaml
    - include: subplays/boost.yaml
    - include: subplays/yaml-cpp.yaml
    - include: subplays/swig.yaml

    - name: deploy toolchain file
      copy:
        src: "newfiles/{{ puppetlabs_build_dir }}/pl-build-toolchain.cmake"
        dest: "{{ puppetlabs_build_dir }}"
